### ISSUE TITLE
Scalling zed damage with zed health?

### ISSUE THREAD

**Issue by Zorrototo** [notblackout/kf2-controlled-difficulty#2]
Hello I'm using the issue system to ask you this, but would it be possible to add a feature to modify also the damage that zeds do. I can see you are able to change zed health, zed numbers, but I don't see a way to modify damage zeds do. Is this me or is this feature not available?

**Comment by LazyT1ger** [comment]
While this is not currently possible with Controlled Difficulty by itself, it is possible with a CD compatible Mutator called Zed Manager that allows you to create/modify zeds. You can find that mutator here: https://steamcommunity.com/sharedfiles/filedetails/?id=1169610792

**Comment by Zorrototo** [comment]
OK thanks for the info. Hope you can manage to expand even more the CD mutator though :)
